name: weatherpal
description: "A Flutter weather app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version information
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.0.5
  cached_network_image: ^3.2.1
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.0.17
  rive: ^0.13.13 # For advanced and interactive weather animations
  weather_icons: ^3.0.0 # For weather-related icons
  google_fonts: ^6.2.1 # For modern fonts
  cupertino_icons: ^1.0.6
  flutter_weather_bg_null_safety: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets such as icons and animations here
  assets:
    - assets/icons/
    - assets/animations/
